args=commandArgs(trailingOnly=TRUE)
j = as.integer(args[[1]])
PCmat_orig<- readRDS('PCs/PCmat_orig.rds')
library(rmetalog)
source('blockwisePCA_R_engine.R')
set.seed(j)
meta_j<-metalog(PCmat_orig[,j], term_limit=5, step_len=.01)
saveRDS(meta_j,sprintf('PCs/metalog_%d.rds',j) )
H_j<-hidden_normalPC(ref_PC= PCmat_orig[,j], target_metalog=meta_j, term=5)
saveRDS( H_j, sprintf('PCs/PChidden_normal%d.rds',j))
